
#url: 'jdbc:sqlite:memory:myDb?cache=shared'

ethnode:
  httpAddress: 'http://localhost:8545'
spring:
  datasource:
    url: jdbc:sqlite:chains.db
    driver-class-name: org.sqlite.JDBC
    username: "sa"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLiteDialect
